CREATE
EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS alert_tg_bot;

CREATE TABLE IF NOT EXISTS alert_tg_bot.provider_terminal_thread (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id    CHARACTER VARYING NOT NULL,
    terminal_id    CHARACTER VARYING NOT NULL,
    thread_id      INTEGER,
    provider_name  CHARACTER VARYING,
    terminal_name  CHARACTER VARYING,
    name           CHARACTER VARYING,

    CONSTRAINT provider_terminal_thread_provider_terminal_uk UNIQUE (provider_id, terminal_id)
);